### ISSUE TITLE
Issue with `set_output`?

### ISSUE THREAD

**Issue by ericphanson** [julia-actions/GitHubActions.jl#31]
I think maybe it needs an `EOF` for multiline outputs, according to this post: https://medium.com/@ibraheemabukaff/github-actions-exporting-multi-line-one-line-value-environment-variable-5bb86d01e866. I'm seeing an issue [here](https://github.com/JuliaRegistries/General/actions/runs/5469675866/jobs/9960197252#step:4:132):
```
##[debug]Set output content = **New package: ConstantRNGs v0.0.1**
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'ConstantRNGs: A simple deterministic RNG, for cases when you need high efficiency and don't care about randomness'
##[debug]System.Exception: Invalid format 'ConstantRNGs: A simple deterministic RNG, for cases when you need high efficiency and don't care about randomness'
##[debug]   at GitHub.Runner.Worker.EnvFileKeyValuePairs.GetEnumerator()+MoveNext()
##[debug]   at GitHub.Runner.Worker.SetOutputFileCommand.ProcessCommand(IExecutionContext context, String filePath, ContainerInfo container)
##[debug]   at GitHub.Runner.Worker.FileCommandManager.ProcessFiles(IExecutionContext context, ContainerInfo container)
##[debug]Finishing: Collect Zulip info
```

**Comment by SaschaMann** [comment]
I wasn't aware you could even set multiline outputs 😅 

Changing `set_output` to match `set_env` should do the trick. Ideally with a random EOF token as in #26 (if someone happens to know how to fix those tests) or the current version: https://github.com/julia-actions/GitHubActions.jl/blob/b796c4be1bfaa2059ece6a24e2ee1990a3ee0379/src/GitHubActions.jl#L188-L196
